"""Laue group symmetry operators and inverse pole figure fundamental sectors.

Only the Laue groups needed for the crystal structures that polyhedral template
matching can identify are implemented.  Each group is described by

* the proper rotations of the group (the improper operations are accounted for
  by also considering ``-v``, since an inverse pole figure colours *axes*), and
* the fundamental sector, given by a set of bounding plane normals and the
  sector vertices.

The sector definitions follow the standard EDAX/TSL and MTEX convention, so
that the resulting colour keys are directly comparable with EBSD orientation
maps.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

__all__ = ["LAUE_GROUPS", "LaueGroup", "get_laue_group"]


def _unit(v: np.ndarray) -> np.ndarray:
    v = np.atleast_2d(np.asarray(v, dtype=float))
    return v / np.linalg.norm(v, axis=-1, keepdims=True)


def _rotation(axis, angle_deg: float) -> np.ndarray:
    axis = np.asarray(axis, dtype=float)
    axis = axis / np.linalg.norm(axis)
    t = np.radians(angle_deg)
    k = np.array(
        [
            [0.0, -axis[2], axis[1]],
            [axis[2], 0.0, -axis[0]],
            [-axis[1], axis[0], 0.0],
        ]
    )
    return np.eye(3) + np.sin(t) * k + (1.0 - np.cos(t)) * k @ k


def _close_group(generators) -> np.ndarray:
    """Return every proper rotation generated by *generators*."""
    ops = [np.eye(3)]
    queue = list(ops)
    while queue:
        current = queue.pop()
        for gen in generators:
            candidate = gen @ current
            if not any(np.allclose(candidate, op, atol=1e-8) for op in ops):
                ops.append(candidate)
                queue.append(candidate)
    return np.array(ops)


@dataclass(frozen=True)
class LaueGroup:
    """A Laue group together with its inverse pole figure fundamental sector."""

    name: str
    #: Proper rotations of the group, shape (n, 3, 3).
    operators: np.ndarray
    #: Outward normals bounding the fundamental sector, shape (m, 3).
    sector_normals: np.ndarray
    #: Sector vertices, shape (3, 3).  Coloured red, green and blue in order.
    sector_vertices: np.ndarray
    #: Labels for the vertices, used by the legend.
    vertex_labels: tuple[str, str, str]
    #: True when directions should be labelled with four Miller-Bravais indices.
    hexagonal_indices: bool = False
    center: np.ndarray = field(init=False)

    def __post_init__(self) -> None:
        center = _unit(self.sector_vertices.mean(axis=0))[0]
        object.__setattr__(self, "center", center)

    @property
    def n_operators(self) -> int:
        return len(self.operators)

    def in_sector(self, v: np.ndarray, tol: float = 1e-9) -> np.ndarray:
        """Boolean mask of the directions *v* that lie inside the sector."""
        v = np.atleast_2d(v)
        return np.all(v @ self.sector_normals.T >= -tol, axis=-1)

    def reduce(self, v: np.ndarray, chunk_size: int = 200_000) -> np.ndarray:
        """Move directions *v* into the fundamental sector.

        Parameters
        ----------
        v
            Crystal directions, shape (n, 3).  They need not be normalised.
        chunk_size
            Directions are processed in chunks to bound peak memory use, which
            matters for the multi-million atom configurations this package is
            meant for.

        Returns
        -------
        numpy.ndarray
            Symmetrically equivalent unit directions inside the sector,
            shape (n, 3).
        """
        v = np.atleast_2d(np.asarray(v, dtype=float))
        out = np.empty_like(v)
        for start in range(0, len(v), chunk_size):
            block = _unit(v[start : start + chunk_size])
            # (n_ops, n, 3) for +v and -v: the Laue group adds the inversion.
            equivalent = np.concatenate(
                [np.einsum("oij,nj->oni", self.operators, block)] * 1
                + [np.einsum("oij,nj->oni", -self.operators, block)],
                axis=0,
            )
            # Distance to the most violated sector boundary; >= 0 means inside.
            margin = np.min(equivalent @ self.sector_normals.T, axis=-1)
            best = np.argmax(margin, axis=0)
            out[start : start + chunk_size] = equivalent[best, np.arange(len(block))]
        return out


def _hex_vertices() -> np.ndarray:
    return np.array(
        [
            [0.0, 0.0, 1.0],  # [0001] c axis, red
            [1.0, 0.0, 0.0],  # [2-1-10] a axis, green
            [np.cos(np.pi / 6), np.sin(np.pi / 6), 0.0],  # [10-10] m, blue
        ]
    )


_CUBIC = LaueGroup(
    name="m-3m",
    operators=_close_group([_rotation([0, 0, 1], 90), _rotation([1, 1, 1], 120)]),
    sector_normals=_unit([[1.0, -1.0, 0.0], [-1.0, 0.0, 1.0], [0.0, 1.0, 0.0]]),
    sector_vertices=_unit([[0, 0, 1], [1, 0, 1], [1, 1, 1]]),
    vertex_labels=("001", "101", "111"),
)

_HEXAGONAL = LaueGroup(
    name="6/mmm",
    operators=_close_group([_rotation([0, 0, 1], 60), _rotation([1, 0, 0], 180)]),
    sector_normals=_unit(
        [[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [0.5, -np.sqrt(3) / 2, 0.0]]
    ),
    sector_vertices=_hex_vertices(),
    vertex_labels=("0001", "2-1-10", "10-10"),
    hexagonal_indices=True,
)

_TETRAGONAL = LaueGroup(
    name="4/mmm",
    operators=_close_group([_rotation([0, 0, 1], 90), _rotation([1, 0, 0], 180)]),
    sector_normals=_unit(
        [[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [np.sqrt(0.5), -np.sqrt(0.5), 0.0]]
    ),
    sector_vertices=_unit([[0, 0, 1], [1, 0, 0], [1, 1, 0]]),
    vertex_labels=("001", "100", "110"),
)

_TRIGONAL = LaueGroup(
    name="-3m",
    operators=_close_group([_rotation([0, 0, 1], 120), _rotation([1, 0, 0], 180)]),
    sector_normals=_unit(
        [
            [0.0, 0.0, 1.0],
            [0.5, np.sqrt(3) / 2, 0.0],
            [0.5, -np.sqrt(3) / 2, 0.0],
        ]
    ),
    sector_vertices=_unit(
        [
            [0, 0, 1],
            [np.cos(-np.pi / 6), np.sin(-np.pi / 6), 0.0],
            [np.cos(np.pi / 6), np.sin(np.pi / 6), 0.0],
        ]
    ),
    vertex_labels=("0001", "10-10", "01-10"),
    hexagonal_indices=True,
)

_ORTHORHOMBIC = LaueGroup(
    name="mmm",
    operators=_close_group([_rotation([0, 0, 1], 180), _rotation([1, 0, 0], 180)]),
    sector_normals=_unit([[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]]),
    sector_vertices=_unit([[0, 0, 1], [1, 0, 0], [0, 1, 0]]),
    vertex_labels=("001", "100", "010"),
)

LAUE_GROUPS: dict[str, LaueGroup] = {
    g.name: g for g in (_CUBIC, _HEXAGONAL, _TETRAGONAL, _TRIGONAL, _ORTHORHOMBIC)
}

_ALIASES = {
    "cubic": "m-3m",
    "m3m": "m-3m",
    "oh": "m-3m",
    "hexagonal": "6/mmm",
    "hex": "6/mmm",
    "d6h": "6/mmm",
    "tetragonal": "4/mmm",
    "d4h": "4/mmm",
    "trigonal": "-3m",
    "d3d": "-3m",
    "orthorhombic": "mmm",
    "d2h": "mmm",
}


def get_laue_group(name: str) -> LaueGroup:
    """Look up a Laue group by symbol (``6/mmm``) or alias (``hexagonal``)."""
    key = name.strip().lower()
    key = _ALIASES.get(key, key)
    try:
        return LAUE_GROUPS[key]
    except KeyError:
        raise KeyError(
            f"unknown Laue group {name!r}; available: "
            + ", ".join(sorted(LAUE_GROUPS)) 
        ) from None
